### ISSUE TITLE
Incorrect Variable Names in Custom Fields Documentation

### ISSUE THREAD

**Issue by Kvrnn** [invoiceninja/invoiceninja.github.io#128]
## Context

I’m self-hosting Invoice Ninja via Docker using the image `invoiceninja/invoiceninja:5` on version `v5.10.44`. 
I ran into an issue with the variable names in the custom fields documentation, specifically when trying to set the `Number Pattern` for invoices.

## Issue

The documentation mentions variables like [`$client1`, `$client2`, and `$client3`](https://github.com/invoiceninja/invoiceninja.github.io/blame/c30250d0f215f6d559bbd58873a872a8e4e37cac/source/en/custom-fields.md#L391) , but they don’t work as expected. 
Instead, the correct variables seem to be `$client_custom1`, `$client_custom2` ... etc

### Screenshots:
1. **Invoice Number Pattern Setting**
![image](https://github.com/user-attachments/assets/902ca0ff-3179-4eae-a60f-90bd08c5d702)

3. **Generated Invoice Numbers**
![image](https://github.com/user-attachments/assets/d6ee61bc-41b9-4c48-bf61-309e25aa08f4)

Has anyone else encountered this issue or am I doing something wrong?

**Comment by turbo124** [comment]
Can you reference the documentation which states $client1 as available for number patterns?

I do not see it listed here:

https://invoiceninja.github.io/en/advanced-settings/#generated_numbers

**Comment by Kvrnn** [comment]
It's under the `Click here to see all variables` pointing to https://invoiceninja.github.io/en/custom-fields/#custom-fields. 
But seeing the link you sent, it makes sense now. Thank you

![image](https://github.com/user-attachments/assets/027660d4-a7e5-4bd2-830c-f86eec515806)
