### ISSUE TITLE
Self Hosted Installation: Queue configuration results in multiple `artisan queue:work`

### ISSUE THREAD

**Issue by kevinoid** [invoiceninja/invoiceninja.github.io#56]
The [Self Hosted Installation page](https://invoiceninja.github.io/docs/self-host-installation/) documents queue configuration with https://github.com/invoiceninja/invoiceninja.github.io/blob/3121a28580e2a0b4f0beb04aeafafb240536ea23/source/docs/self-host-installation.md?plain=1#L188-L194

> If you have root access to your system, then simply follow the Laravel [guide](https://laravel.com/docs/8.x/queues#supervisor-configuration) to configure the supervisor service to start and restart your queue.
>
> You will then need to update the QUEUE_CONNECTION variable in the .env file as follows:
>
> ```
> QUEUE_CONNECTION=database
> ```

However, setting `QUEUE_CONNECTION=database` will cause queue:work to be run from cron and queue:restart every 5 minutes:  https://github.com/invoiceninja/invoiceninja/blob/019e3c0068dba809a39c0b11f83fcbc82c86e231/app/Console/Kernel.php#L92-L97 This results in `artisan queue:work` being invoked from supervisor (as per the [guide](https://laravel.com/docs/8.x/queues#supervisor-configuration)) and cron simultaneously, and both processes to exit every 5 minutes, which is seems unnecessary.  Is this really the desired result?  Should administrators set `INTERNAL_QUEUE_ENABLED=false` once supervisor is configured to avoid this?

Thanks,
Kevin

**Comment by turbo124** [comment]
Hi Kevin,

Yes that is true. The fix would be to set that env var to false, i'll update the docs.

**Comment by turbo124** [comment]
I've updated the docs, thanks for the suggestion.

**Comment by kevinoid** [comment]
Looks great, thanks @turbo124!
